.env.docker
.env.example
Makefile
docker/set-admin.sh
fittrackee/__init__.py
fittrackee/__main__.py
fittrackee/emails/email.py
fittrackee/users/users.py
pyproject.toml

Fixes and improvements

---

docsrc/source/installation.rst

Add client_max_body_size note to example nginx config

---

.gitignore
Makefile
db/create.sql
fittrackee/config.py
fittrackee/tests/application/test_config.py
fittrackee/tests/conftest.py
fittrackee/tests/fixtures/fixtures_app.py
fittrackee/tests/oauth2/test_oauth2_client.py
fittrackee/tests/test_utils.py
poetry.lock
pyproject.toml

add parallelization for tests that are run locally (maximum 4 workers):
```shell
$ make test-python PYTEST_ARGS="-p no:warnings -n auto --maxprocesses=4"
```
Note: for now, not working w/ e2e tests

Tests parallelization

---

.github/workflows/.tests-python.yml
docs/_sources/installation.rst.txt

Drop PostgreSQL 10 support

---

docsrc/source/cli.rst
fittrackee/tests/users/test_users_utils.py
fittrackee/users/auth.py
fittrackee/users/commands.py
fittrackee/users/exceptions.py
fittrackee/users/utils/admin.py

Add CLI command to create user account

---

CONTRIBUTING.md

Fix link to installation instructions.

Minor fix in CONTRIBUTING.md

---

.env.docker
.env.example

see https://github.com/SamR1/FitTrackee/issues/318

remove darksky from available weather providers in .env

---

.github/workflows/.tests-python.yml

PostgreSQL 16 has been released: https://www.postgresql.org/about/news/postgresql-16-released-2715/

CI - Add PostgreSQL 16

---

fittrackee/emails/email.py
fittrackee/tests/emails/test_email_service.py

Handle encoded password in EMAIL_URL

---

.github/workflows/.tests-python.yml
fittrackee/__init__.py
fittrackee/application/models.py
fittrackee/migrations/commands.py
fittrackee/oauth2/clean.py
fittrackee/oauth2/models.py
fittrackee/tests/users/test_users_model.py
fittrackee/users/models.py
fittrackee/users/utils/token.py
fittrackee/utils.py
fittrackee/workouts/models.py
poetry.lock
pyproject.toml

see #355 
**NOTE**:
- to do in a next version: add typing on models

Update FlaskSQLAlchemy and SQLAlchemy

---

.github/workflows/.tests-python.yml
pyproject.toml

Python 3.12.0 has been released: https://www.python.org/downloads/release/python-3120/

CI - Add Python 3.12

---

fittrackee/__init__.py
fittrackee/application/models.py
fittrackee/migrations/commands.py
fittrackee/oauth2/clean.py
fittrackee/oauth2/models.py
fittrackee/tests/users/test_users_model.py
fittrackee/users/models.py
fittrackee/users/utils/token.py
fittrackee/utils.py
fittrackee/workouts/models.py
poetry.lock
pyproject.toml

see https://github.com/SamR1/FitTrackee/issues/355#issuecomment-1746908081
revert partially PR https://github.com/SamR1/FitTrackee/pull/435

API - FlaskSQLAlchemy update rollback

---

.github/workflows/.tests-python.yml
docsrc/source/installation.rst

Drop PostgreSQL 11 support

---

.github/workflows/.tests-python.yml
fittrackee/migrations/commands.py
poetry.lock
pyproject.toml

Fix database upgrade

---

.github/workflows/.tests-python.yml
fittrackee/migrations/commands.py
poetry.lock
pyproject.toml

see https://github.com/SamR1/FitTrackee/issues/504#issuecomment-1993710683

CLI - update database commands

---

docsrc/source/cli.rst
fittrackee/__main__.py
pyproject.toml

Remove deprecated commands

---

fittrackee/equipments/equipments.py
fittrackee/equipments/utils.py
fittrackee/tests/equipments/test_equipments_api.py
fittrackee/tests/equipments/test_equipments_model.py
fittrackee/tests/equipments/test_equipments_utils.py
fittrackee/tests/fixtures/fixtures_users.py
fittrackee/tests/users/test_auth_api.py
fittrackee/tests/users/test_users_api.py
fittrackee/tests/users/test_users_model.py
fittrackee/tests/workouts/test_sports_api.py
fittrackee/tests/workouts/test_sports_model.py
fittrackee/tests/workouts/test_utils/test_gpx.py
fittrackee/tests/workouts/test_workouts_api_1_post.py
fittrackee/tests/workouts/test_workouts_api_2_patch.py

Fix on equipments (https://github.com/SamR1/FitTrackee/pull/336) :
- for now only one equipment per sport or workout
- tests fixtures renaming

Equipments fix

---

fittrackee/equipments/equipments.py
fittrackee/tests/equipments/test_equipments_api.py

see https://github.com/SamR1/FitTrackee/pull/336

check sports and equipment type when adding/updating equipment

---

fittrackee/__init__.py
fittrackee/application/models.py
fittrackee/migrations/commands.py
fittrackee/oauth2/clean.py
fittrackee/oauth2/models.py
fittrackee/users/utils/token.py
fittrackee/utils.py

see https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#x-2-x-migration-overview
(no update to SQLAlchemy 2.0 in this PR)

API - prepare SQLAlchemy migration

---

.github/workflows/.tests-python.yml

PostgreSQL 17 has been released: https://www.postgresql.org/about/news/postgresql-17-released-2936/

CI - add PostgreSQL 17

---

docker-compose.yml

Hey, 
I hope this is not 'bad manners' to just PR something, but I had trouble starting the docker, found the mistake and was able to fix it. 
This is my first PR and I always wanted to learn how this works out. Hope you are fine with that ;)I have not learnt this and so I am often unable to help and useless when a problems arise. 
BUG:
The parameter (hope this is the right word?) is wrong, so docker tried to create the fallback folder, which failes, if docker is not run with root privileges. 
Rename the parameters, works like a charm.
Best wishes from Germany

fixed docker-compose.yaml

---

Dockerfile
docker-compose.yml

- update Poetry version from 1.8.5 to 2.1.1
- fix files permissions
- add missing volume to workers container (required for user data export)
- \+ other minor fixes

update docker files

---

docsrc/source/installation.rst

LMK if this isn't the right place to update the docs!

docs(install): Add WEATHER_API_PROVIDER to weather section

---

fittrackee/tests/fixtures/fixtures_workouts.py
fittrackee/tests/workouts/test_utils/test_gpx.py
fittrackee/tests/workouts/test_workouts_model.py
fittrackee/workouts/constants.py
fittrackee/workouts/models.py
fittrackee/workouts/utils/convert.py
fittrackee/workouts/utils/gpx.py

API - fix cadence value when displayed in steps per minute (spm)

---

fittrackee/tests/fixtures/fixtures_workouts.py
fittrackee/tests/workouts/test_services/from_file/test_workout_gpx_creation_service.py
fittrackee/tests/workouts/test_utils/test_gpx.py
fittrackee/tests/workouts/test_workouts_api_0_get_workout.py
fittrackee/workouts/services/workout_from_file/workout_gpx_creation_service.py
fittrackee/workouts/utils/gpx.py
fittrackee/workouts/workouts.py

Handle cadence float values

---

fittrackee/comments/utils.py
fittrackee/tests/comments/test_utils.py

API - fix URL in comments when containing @ matching a mention

---

fittrackee/tests/workouts/test_workouts_model.py
fittrackee/workouts/models.py

API - return records when getting workouts

---

.github/workflows/.tests-and-publish-python.yml
docsrc/source/installation.rst
mypy.ini
poetry.lock
pyproject.toml

Drop support for python 3.9
