- fittrackee/workouts/utils_gpx.py
When loading GPX files that have slow movement, such as when hiking in more vertical conditions, the default `stopped_speed_threshold` of 1km/hr is too high. In the GPXPY tests, 0.1km/hr is used: https://github.com/tkrajina/gpxpy/blob/e3733bbd59d11bcbf089f30b286286fcd728bb46/gpxpy/gpx.py#L848
This updates the stop detection to 0.1km/hr to track stops.
> Added stopped_speed_threshold to support slow movement

- fittrackee/tests/fixtures/fixtures_workouts.py
- fittrackee/tests/workouts/test_utils/test_gpx.py
- fittrackee/workouts/utils/gpx.py
While inspecting the gpx handling, I found a bug:
The variable `stopped_time_between_seg` contains only the time between the _latest two segments_ and passes them to `get_gpx_data`.
This is not an issue, if the track contains only one or two segments. But if there are more, the additional calculations are incorrect.
The changed code aggregates the time between all segments now.
> Bugfix: Incorrect duration with track containing multiple segments

- fittrackee/tests/workouts/test_utils/test_workouts.py
- fittrackee/workouts/utils/workouts.py
see #247 
Note: it fixes only next imported workouts.
> API - save segment duration w/o microseconds

- docsrc/source/installation.rst
- fittrackee/__main__.py
- pyproject.toml
Since Flask update to 2.2.x, `fittrackee_worker` is not working anymore.
This entrypoint is now disabled, since it is just a duplicate command for `flask worker` ([flask-dramatiq CLI](https://flask-dramatiq.readthedocs.io/en/latest/cli.html)).
It will be completely removed in a next version.
> Disable worker entry point

- Dockerfile
- Makefile
- Makefile.config
- docker-compose-dev.yml
- docker/lint-python.sh
> Docker - install fittrackee in a virtualenv

- .github/workflows/.tests-javascript.yml
- .github/workflows/.tests-python.yml
see warnings on CI:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-node@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> CI - update actions version

- docsrc/source/installation.rst
- fittrackee/tests/users/test_users_api.py
- fittrackee/tests/users/test_users_utils.py
- fittrackee/users/users.py
- fittrackee/users/utils/admin.py
- fittrackee_client/src/locales/de/api.json
- fittrackee_client/src/locales/en/api.json
- fittrackee_client/src/locales/es/api.json
- fittrackee_client/src/locales/fr/api.json
- fittrackee_client/src/locales/gl/api.json
- fittrackee_client/src/locales/it/api.json
- fittrackee_client/src/locales/nl/api.json
- fittrackee_client/src/locales/pl/api.json
> Fix various typos

- .github/workflows/.tests-python.yml
`pytest-html` latest version removed `py` as a dependency (see pytest-selenium/issues/313)
> CI - fix e2e tests with packaged version

- docs/en/_sources/installation.rst.txt
- docs/en/installation.html
- docs/fr/_sources/installation.rst.txt
- docs/fr/installation.html
- docsrc/gettext/docs.pot
- docsrc/locales/en/LC_MESSAGES/docs.po
- docsrc/locales/fr/LC_MESSAGES/docs.po
- docsrc/source/installation.rst
- fittrackee/config.py
- fittrackee/tests/workouts/test_utils/test_maps.py
see https://github.com/openstreetmap/operations/issues/737
(replaces #425, thanks @astridx)
> Update default tile server

- poetry.lock
- pyproject.toml
see #441 
pin Flask-SQLAlchemy to 3.0.5 (latest version compatible w/ Flask 3.0 and SQLalchemy 1.4) 
Note: version 3.0.5 has already been pinned to `poetry.lock`
> Pin Flask-SQLAlchemy version

- poetry.lock
- pyproject.toml
**Note** : gpxpy [v1.6.0](https://github.com/tkrajina/gpxpy/blob/dev/CHANGELOG.md#v160) now ignores points without elevation when calculating ascent/descent (fix https://github.com/SamR1/FitTrackee/issues/224)
> update gpxpy to 1.6.1

- pyproject.toml
See https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
This would help avoid patching the repository when packaging it in nixpkgs: https://github.com/NixOS/nixpkgs/blob/e613b63475ada269627724723c19c5e8e4132dea/pkgs/servers/geospatial/fit-trackee/default.nix#L52-L53
> Build - use poetry-core instead of poetry

- Makefile
- docsrc/source/installation.rst
The `--no-dev` option is deprecated, since Poetry uses groups for dependencies (version [ 1.2](https://python-poetry.org/blog/announcing-poetry-1.2.0/#dependency-groups), released on August 31, 2022).
Use the `--only main` notation for `make install-python`.
> Update `install-python` command

- fittrackee/tests/users/test_users_export_data.py
- fittrackee/users/export_data.py
`datetime.now()` was used instead of `datetime.utcnow()` to filter user data export (`UserDataExport.created_at` is initaliazed with  `datetime.utcnow()`).
**Note**: [`datetime.utcnow()` is now deprecated](https://docs.python.org/3/whatsnew/3.12.html#deprecated). It will be replaced in a next version of **FitTrackee**.
> CLI - fix limit for user data export cleanup

- fittrackee/emails/email.py
- fittrackee/tests/emails/test_email_service.py
E.g. `foobar@example.com` would otherwise be replaced with `foobar%40example.com`.
> email username may contain special characters

- fittrackee/emails/email.py
- fittrackee/tests/emails/test_email_service.py
Some SMTP providers may reject emails as spam due to missing `Message-ID` header : 
```python
File "/usr/lib/python3.12/smtplib.py", line 897, in sendmail
raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'5.7.1 Spam Detected - Mail Rejected.  Please see our policy at: xxx')
```
> Fix email sending by adding 'Message-ID'

- .github/workflows/.tests-python.yml
- docsrc/source/installation.rst
- poetry.lock
- pyproject.toml
> API - drop support for Python 3.8

- fittrackee/tests/workouts/test_workouts_api_0_get_workouts.py
- fittrackee/tests/workouts/test_workouts_model.py
- fittrackee/workouts/models.py
- fittrackee/workouts/workouts.py
To avoid fetching unnecessary data when displaying workouts list, equipment is not returned since 0.9.0b1.
This behavior prevents 3rd party apps like this [script](https://codeberg.org/SamR1/workouts-equipments-updater) to update workouts equipment.
This PR add a parameter to return workouts with equipment when provided.
> api - get workouts list with equipment

- .github/workflows/.e2e-tests.yml
- .github/workflows/.tests-python.yml
Add jobs to publish Python distribution on PyPI and initiate GitHub draft release when a release tag is pushed.
source: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
> Publish package on PyPI using GitHub Actions workflow

- docsrc/source/cli.rst
- fittrackee/tests/users/test_auth_api.py
- fittrackee/tests/users/test_users_commands.py
- fittrackee/tests/users/test_users_service.py
- fittrackee/users/commands.py
- fittrackee/users/users_service.py
Add `--role` option to create user command in order to create user with a given role:
```shell
$ ftcli users create --help
Usage: ftcli users create [OPTIONS] USERNAME
Create an active user account.
Options:
--email TEXT                    User email.  [required]
--password TEXT                 User password. If not provided, a random
password is generated.
--lang TEXT                     User preference for interface language (two-
letter code, ISO 639-1). If not provided or
not supported, it falls back to English
('en'). Supported languages: bg, cs, de, en,
es, eu, fr, gl, it, nb, nl, pl, pt, ru.
--role [owner|admin|moderator|user]
Set user role.
--help                          Show this message and exit.
```
> CLI - create user with provided role

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .gitignore
Adds a [Bug Report Issue Form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).
Fairly generic but hopefully captures key information. Its not essential that people use it but thought it would be useful as I forgot to include my `.env` in a recent report (#716).
I've also taken the liberty to exclude temporary files that Emacs creates to `.gitignore` so they don't get included.
> feature: Adds YAML bug report template

- fittrackee/config.py
- fittrackee/tests/fixtures/fixtures_workouts.py
- fittrackee/tests/workouts/mixins.py
- fittrackee/tests/workouts/test_services/from_file/test_workout_gpx_creation_service.py
- fittrackee/tests/workouts/test_services/from_file/test_workout_kml_creation_service.py
- fittrackee/tests/workouts/test_services/from_file/test_workout_tcx_creation_service.py
- fittrackee/tests/workouts/test_services/test_workouts_from_file_creation_service.py
- fittrackee/tests/workouts/test_workouts_api_1_post.py
- fittrackee/workouts/services/__init__.py
- fittrackee/workouts/services/workout_from_file/__init__.py
- fittrackee/workouts/services/workout_from_file/workout_tcx_creation_service.py
- fittrackee/workouts/services/workouts_from_file_creation_service.py
- fittrackee_client/src/components/Workout/WorkoutEdition.vue
- pyproject.toml
see https://github.com/SamR1/FitTrackee/issues/529
Init support for TCX files:
- files are converted in gpx format to be analyzed with `gpxpy`
- generated gpx file contains one track containing one segment per activity
- for now only time, longitude, latitude and elevation are handled (no heart rate for instance)
- invalid values for elevation are ignored as workaround
> Init TCX support

- Dockerfile
- Dockerfile-dev
- poetry.lock
- pyproject.toml
PyPI does not allow direct dependency.
Therefore the fork of **Static Map** has been published to remove direct dependency.
> fix python package

- fittrackee/tests/workouts/test_services/from_file/test_workout_gpx_creation_service.py
- fittrackee/workouts/services/workout_from_file/workout_gpx_creation_service.py
In version v0.10.x, heart rate and cadence are ignored on workout creation, when points contain several values in addition to `TrackPointExtension`.
Example:
```xml
<trkpt lat="redacted"
lon="redacted">
<time>redacted</time>
<ele>redacted</ele>
<extensions>
<speed>13.13</speed>
<cadence>101</cadence>
<heartrate>139</heartrate>
<power>633</power>
<gpxtpx:TrackPointExtension>
<gpxtpx:hr>139</gpxtpx:hr>
<gpxtpx:cad>101</gpxtpx:cad>
</gpxtpx:TrackPointExtension>
</extensions>
</trkpt>
```
This PR fixes the calculation of max and average values for HR and cadence.
> Fix hr and cadence values when gpx points contain multiple values in extensions

- fittrackee/application/exceptions.py
- fittrackee/application/utils.py
- fittrackee/tests/application/test_database_utils.py
see #855 
- set isolation level to `SERIALIZABLE` when creating first row in `app_config` table to prevent multiple rows creation
> API - fix app config init to prevent multiple rows creation
